# Generated by Django 5.1.2 on 2024-11-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_membro_alter_feedback_membro_delete_administrador'),
        ('Member_Get_Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='Feedback.membro'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='convidador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to='Feedback.membro'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Feedback.membro')),
            ],
        ),
    ]
