# Generated by Django 5.1.2 on 2024-11-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member_Get_Member', '0002_alter_convite_convidado_alter_convite_convidador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recompensa',
            name='valor',
        ),
    ]
