# Generated by Django 5.1.2 on 2024-11-07 22:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0007_alter_feedback_avaliacao'),
        ('Member_Get_Member', '0003_remove_recompensa_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='convite',
            name='data_expiracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convite',
            name='limite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='convite',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_recebidos', to='Feedback.membro'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('expirado', 'Expirado')], default='pendente', max_length=20),
        ),
    ]
