# Generated by Django 5.1.3 on 2024-11-08 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member_Get_Member', '0004_convite_data_criacao_convite_data_expiracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='convidado',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='link',
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
