# Generated by Django 5.1.2 on 2024-11-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member_Get_Member', '0005_remove_convite_convidado_remove_convite_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='limite',
            field=models.IntegerField(default=10),
        ),
    ]
