# Generated by Django 5.1.2 on 2024-11-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_membro_alter_feedback_membro_delete_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content_type',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
