# Generated by Django 5.1.2 on 2024-11-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_feedback_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content_type',
            new_name='avalição',
        ),
    ]
