# Generated by Django 5.1.2 on 2024-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0004_rename_content_type_feedback_avalição'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avalição',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('sugestão', 'Sugestão')], max_length=10),
        ),
    ]
