# Generated by Django 5.1.2 on 2024-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0006_remove_feedback_avalição_feedback_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='avaliacao',
            field=models.CharField(choices=[('SUGESTAO', 'Sugestao'), ('COMENTARIO', 'Comentario'), ('ERRO', 'Erro')], default='Comentario', max_length=10),
        ),
    ]
